name: Fetcher

on:
  schedule:
    - cron: "*/30 * * * * *" # Run every 30 seconds

jobs:
  run-fetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run fetcher script
        run: |
          chmod +x fetcher.sh
          ./fetcher.sh
      - name: Commit changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add movie_ids_*.json
          git commit -m "Daily fetch on $(date +'%Y-%m-%d')"
          git push
